### ISSUE TITLE
Getting wrong lat long

### ISSUE THREAD

**Issue by nisos-siddharth** [sebastianbaar/cordova-plugin-nativegeocoder#14]
I am developing a hybrid mobile app in ionic2. I want to get lat-long base on the address. 
Following is my code:

`this.nativeGeocoder.forwardGeocode('20 Greenway Rockville Centre NY 11570')
  .then((coordinates: NativeGeocoderForwardResult) => console.log('The coordinates are latitude=' + coordinates.latitude + ' and longitude=' + coordinates.longitude))
  .catch((error: any) => console.log(error));`

On ios, i am getting latitude = 40.661109 and longitude=-73.626429 which is wrong. The correct lat-long is latitude = 40.660858 and longitude=73.626354. 

What could be the issue?

**Comment by sebastianbaar** [comment]
Hi @nisos-siddharth, 

lat: 40... and lon: -73... is correct, that's New York. 
lat: 40... and lon: 73... is somewhere in Asia.

I don't get it. What exactly do you think is going wrong here?

Cheers

**Comment by nisos-siddharth** [comment]
Sorry, it is not longitude=73.626354 it is longitude=-73.626354.
Means if I convert "20 Greenway Rockville Centre NY 11570" this address then expected lat-long is latitude = 40.660858 and longitude=-73.626354. But I get latitude = 40.661109 and longitude=-73.626429 which is wrong.

**Comment by sebastianbaar** [comment]
Ok, but still... there is a variance of approx. 30 meters (http://bit.ly/2zG6BH0) for these lat/longs. I do not think that this is such a bad result...

And however this is not an issue with this plugin but with how Apple and Google process forward geocoding. I have no influence of how Apple is calculating the lat/long for a given address. That's why I don't think it's an issue with this plugin and I will close this issue. If you think I'm wrong just let me know ;-)

Cheers
