### ISSUE TITLE
different places same coordenates

### ISSUE THREAD

**Issue by albe-rosado** [sebastianbaar/cordova-plugin-nativegeocoder#22]
![screenshot from 2018-01-01 21-35-33](https://user-images.githubusercontent.com/18025582/34473515-bc9019d4-ef41-11e7-9f19-9202bb8635df.png)
As the title suggests, I get the same coords for different locations, they are in the same city but far enough.

**Comment by sebastianbaar** [comment]
hey @albe-rosado, the plugin uses the native APIs from iOS (CoreLocation service) and Android (Geocoder). Therefore, this plugin does not have any influence of how the coordinates are calculated. Maybe you should try again with "better" address strings, like street name & house number instead of company names... I'm closing this issue due to the fact that this is not a problem with the plugin itself. Good luck!
Cheers
