### ISSUE TITLE
TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by MRL-00** [sebastianbaar/cordova-plugin-nativegeocoder#31]
I'm getting an `TypeError: Object(...) is not a function` error when trying to use Native Geocoder.

Code is below:

`import { NativeGeocoder, NativeGeocoderOptions, NativeGeocoderReverseResult,` `NativeGeocoderForwardResult } from '@ionic-native/native-geocoder';
  constructor(private Platform: Platform, public loadingCtrl: LoadingController, private router: Router, public natGeo: NativeGeocoder) {}`
`...
let options: NativeGeocoderOptions = {
      useLocale: true,
      maxResults: 5
  };`
  
  `this.natGeo.forwardGeocode('Berlin', options)
    .then((coordinates: NativeGeocoderForwardResult[]) => console.log('The coordinates are latitude=' + coordinates[0].latitude + ' and longitude=' + coordinates[0].longitude))
    .catch((error: any) => console.log(error));
...`

How can I get this to work please?

**Comment by sebastianbaar** [comment]
Hey @MattL-NZ,

please re-post your code as a [code block](https://help.github.com/articles/creating-and-highlighting-code-blocks/). Otherwise it's too hard to read. And please specify the line where the error occurs. Thanks.

Cheers

**Comment by marquish** [comment]
I got the same issue, as i recently updated to ionic 4.4.0 
Any suggestions ?
```
Uncaught TypeError: Object(...) is not a function
    at vendor.js:70033
    at Module../node_modules/@ionic-native/native-geocoder/index.js (vendor.js:70089)
    at __webpack_require__ (runtime.js:84)
    at Module../src/app/app.module.ts (main.js:1753)
    at __webpack_require__ (runtime.js:84)
    at Module../src/main.ts (main.js:2127)
    at __webpack_require__ (runtime.js:84)
    at Object.0 (main.js:2149)
    at __webpack_require__ (runtime.js:84)
    at checkDeferredModules (runtime.js:46)
```

**Comment by sebastianbaar** [comment]
Hey @marquish, 
please fill out the bug template and point out where the error shows up in your code:

Thanks!

--------- 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior or sample code/repo.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Plugin Version**
vX.X.X

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] or Emulator: [e.g. Nexus 7]
 - OS: [e.g. iOS8.1]

**Additional context**
Add any other context about the problem here.

**Comment by sebastianbaar** [comment]
Closed due to inactivity
