### ISSUE TITLE
Native Geocoder . can't able to find “thoroughfare”,“subThoroughfare”

### ISSUE THREAD

**Issue by surajsingh23** [sebastianbaar/cordova-plugin-nativegeocoder#37]

**Comment by sebastianbaar** [comment]
Hey @surajsingh23 , 
please fill out the bug template:

Thanks!

--------- 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior or sample code/repo.

**Expected behavior**
A clear and concise description of what you expected to happen.

**Plugin Version**
vX.X.X

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6] or Emulator: [e.g. Nexus 7]
 - OS: [e.g. iOS8.1]

**Additional context**
Add any other context about the problem here.

**Comment by surajsingh23** [comment]
hey, @sebastianbaar 
my question is why "thoroughfare" and "subThoroughfare" always return a null value?
-------------------------------
**this is my code.**

```
var options = {
      timeout: 5000,
      enableHighAccuracy: true,
    };
    this.geoLocation.getCurrentPosition(options).then(resp => {
      this.latitude = resp.coords.latitude;
      this.longitude = resp.coords.longitude
      this.reverseGeoCoding(resp.coords.latitude, resp.coords.longitude);
    })
  }
  reverseGeoCoding(lat, lng) {
    this.nativeGeocoder.reverseGeocode(lat, lng).then(resp => {
       this.address =  resp[0].subThoroughfare+ " ," resp[0].thoroughfare+ " ," resp[0].subLocality + " ," + resp[0].locality + " ," + resp[0].administrativeArea + " ," + resp[0].countryName + "," + resp[0].postalCode;
    })
  }

```
--------------
**Plugin Version
v3.1.4**
---------
**expected**
 resp[0].subThoroughfare = some value,   resp[0].thoroughfare  = some value;
-------------------
**actual result**
but thoroughfare and subThoroughfare  always return null;
resp[0].subThoroughfare = null,   resp[0].thoroughfare  = null;
 
**Device**
Device: nokia 6.1 Plus, google pixel 3

Thanks!

**Comment by surajsingh23** [comment]
can u please reply

**Comment by sebastianbaar** [comment]
Hey @surajsingh23,

please try again with these location points:
```
public latitude: number =  52.51627;
public longitude: number = 13.37770;
```

This should return a valid thoroughfare (subThoroughfare is empty though - couldn't find a good example for subThoroughfare in the moment but it should be sufficient to fix your problem).

Cheers

**Comment by sebastianbaar** [comment]
Closed due to inactivity
